Документация -- https://docs.scipy.org/doc/numpy/reference/index.html

In [1]:
import numpy as np

## Генерация массива

In [255]:
a = np.array([[0, 1, 2],[3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [256]:
print(type(a)) # Тип переменной
print(a.ndim)  # Количество размерностей массива
print(a.shape) # Размеры
print(a.dtype) # Тип содержимого

<class 'numpy.ndarray'>
2
(2, 3)
int32


In [257]:
np.random.rand(5)

array([ 0.14711039,  0.36703283,  0.49815038,  0.20881376,  0.06505809])

In [258]:
np.random.randint(low=5, high=10)

8

Рандомно задать двумерный массив целых чисел 

In [158]:
n = np.random.randint(10, size=(np.random.randint(2,10),np.random.randint(2,10)))
n

array([[9, 0, 5, 6],
       [4, 2, 6, 6],
       [7, 2, 3, 7],
       [3, 0, 7, 9],
       [6, 4, 6, 8],
       [9, 3, 6, 2]])

Изменить тип элементов в предыдущем массиве на float.

In [159]:
n = np.array(n, dtype='float64')
n

array([[9., 0., 5., 6.],
       [4., 2., 6., 6.],
       [7., 2., 3., 7.],
       [3., 0., 7., 9.],
       [6., 4., 6., 8.],
       [9., 3., 6., 2.]])

Перемешать в нем элементы

In [160]:
np.random.shuffle(n)
n

array([[3., 0., 7., 9.],
       [6., 4., 6., 8.],
       [9., 3., 6., 2.],
       [7., 2., 3., 7.],
       [4., 2., 6., 6.],
       [9., 0., 5., 6.]])

Создать массив из чисел от 0 до 100

In [161]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Создать трехмерный массив, заполненный 0) нулями, 1) единицами.
Создать единичную матрицу.

In [162]:
np.zeros((3,np.random.randint(10),np.random.randint(10)))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [264]:
np.ones((3,np.random.randint(10),np.random.randint(10)))

array([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

In [265]:
np.identity(np.random.randint(2,10))

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

## Cрезы

In [114]:
a = np.random.randint(low=0, high=10, size=(4, 5))
a

array([[9, 5, 8, 3, 5],
       [6, 7, 5, 6, 9],
       [1, 4, 9, 5, 2],
       [3, 2, 3, 5, 2]])

In [115]:
a[1]

array([6, 7, 5, 6, 9])

In [116]:
a[1, 2]

5

In [117]:
a[1][2]

5

Вывести массив, состоящий из 1-3 1) строк, 2) столбцов массива a

In [118]:
a[0:3]

array([[9, 5, 8, 3, 5],
       [6, 7, 5, 6, 9],
       [1, 4, 9, 5, 2]])

In [119]:
a[0:4,0:3]

array([[9, 5, 8],
       [6, 7, 5],
       [1, 4, 9],
       [3, 2, 3]])

Вывести массив, состоящий из 1) строк 2) столбцов массива a с четными индексами

In [120]:
np.array([a[line] for line in range(0,3,2)])

array([[9, 5, 8, 3, 5],
       [1, 4, 9, 5, 2]])

In [121]:
np.array([a[0:5, i] for i in range(0,5,2)]).T

array([[9, 8, 5],
       [6, 5, 9],
       [1, 9, 2],
       [3, 3, 2]])

Занулить 2 столбец массива a

In [122]:
a[:,1] = 0
a

array([[9, 0, 8, 3, 5],
       [6, 0, 5, 6, 9],
       [1, 0, 9, 5, 2],
       [3, 0, 3, 5, 2]])

Вывести массив той же размерности, что и a, где на месте каждого элемента из массива a будет стоять True или False в зависимости от того, больше ли этот элемент 1) 0, 2) 5 

In [123]:
np.array([[True if a[j][i]>0 else False for i in range(5)] for j in range(4)])

array([[ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [124]:
np.array([[True if a[j][i]>5 else False for i in range(5)] for j in range(4)])

array([[ True, False,  True, False, False],
       [ True, False, False,  True,  True],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

Составить массив из элементов массива a, больших 5

In [125]:
a[a>5]

array([9, 8, 6, 6, 9, 9])

## Линейная алгебра

Найти минимальный и максимальный элементы массива a, среднее арифметическое, медиану, сумму элементов и стандартно отклонение

In [126]:
np.amax(a)

9

In [127]:
np.amin(a)

0

In [128]:
np.mean(a)

4.05

In [129]:
np.median(a)

4.0

In [130]:
np.sum(a)

81

In [131]:
np.std(a)

3.0573681492420897

In [132]:
a

array([[9, 0, 8, 3, 5],
       [6, 0, 5, 6, 9],
       [1, 0, 9, 5, 2],
       [3, 0, 3, 5, 2]])

Отсортировать элементы в массиве a 1) по строкам 2) по столбцам

In [133]:
np.sort(a, axis=1)

array([[0, 3, 5, 8, 9],
       [0, 5, 6, 6, 9],
       [0, 1, 2, 5, 9],
       [0, 2, 3, 3, 5]])

In [134]:
np.sort(a, axis=0)

array([[1, 0, 3, 3, 2],
       [3, 0, 5, 5, 2],
       [6, 0, 8, 5, 5],
       [9, 0, 9, 6, 9]])

Транспонировать матрицу a

In [135]:
a.T

array([[9, 6, 1, 3],
       [0, 0, 0, 0],
       [8, 5, 9, 3],
       [3, 6, 5, 5],
       [5, 9, 2, 2]])

Произвести умножение матриц

In [136]:
A = np.matmul(a, a.T)
A

array([[179, 157, 106,  76],
       [157, 178,  99,  81],
       [106,  99, 111,  59],
       [ 76,  81,  59,  47]])

Найти ранг матрицы, ее определитель

In [137]:
np.linalg.matrix_rank(A)

4

In [138]:
np.linalg.det(A)

2274064.0000000014

Решить систему линейных уравнений, заданных матрицей

In [139]:
b = np.array([2,3,7,0])
x = np.linalg.solve(A,b)

проверим правильность решения

In [140]:
np.allclose(np.dot(A, x), b)

True

## Операции

Выполнить поэлементное сложение и умножение матриц

In [141]:
B = np.random.randint(low=0, high=10, size=(4, 4))
B

array([[2, 4, 4, 2],
       [2, 7, 3, 6],
       [8, 4, 6, 8],
       [7, 4, 0, 0]])

In [142]:
A + B

array([[181, 161, 110,  78],
       [159, 185, 102,  87],
       [114, 103, 117,  67],
       [ 83,  85,  59,  47]])

In [143]:
A * B

array([[ 358,  628,  424,  152],
       [ 314, 1246,  297,  486],
       [ 848,  396,  666,  472],
       [ 532,  324,    0,    0]])

Превратить одномерный массив в двумерный с сохранением элементов

In [144]:
c = np.random.randint(low=0, high=10, size=(1,8))
c

array([[5, 9, 1, 8, 2, 0, 1, 3]])

In [145]:
np.reshape(c, (2,np.size(c)//2))

array([[5, 9, 1, 8],
       [2, 0, 1, 3]])

Добавить 1) строки 2) столбцы одного массива в другой (слить в один)

In [146]:
np.concatenate((A, B), axis=0)

array([[179, 157, 106,  76],
       [157, 178,  99,  81],
       [106,  99, 111,  59],
       [ 76,  81,  59,  47],
       [  2,   4,   4,   2],
       [  2,   7,   3,   6],
       [  8,   4,   6,   8],
       [  7,   4,   0,   0]])

In [147]:
np.concatenate((A, B), axis=1)

array([[179, 157, 106,  76,   2,   4,   4,   2],
       [157, 178,  99,  81,   2,   7,   3,   6],
       [106,  99, 111,  59,   8,   4,   6,   8],
       [ 76,  81,  59,  47,   7,   4,   0,   0]])

Заменить нулевые значения в массиве на среднее по строке

In [148]:
B

array([[2, 4, 4, 2],
       [2, 7, 3, 6],
       [8, 4, 6, 8],
       [7, 4, 0, 0]])

In [149]:
np.where(np.equal(B,0), np.ma.array(B, mask=np.equal(B,0)).mean(axis=0), B)

array([[2.        , 4.        , 4.        , 2.        ],
       [2.        , 7.        , 3.        , 6.        ],
       [8.        , 4.        , 6.        , 8.        ],
       [7.        , 4.        , 4.33333333, 5.33333333]])

Поэкспериментировать со слиянием двух матриц. Добавить элементы одной на определенное место в другой (допустим, 3 и 4 столбец). Что, если матрицы трехмерные? Если не подходят размерности?

In [150]:
A

array([[179, 157, 106,  76],
       [157, 178,  99,  81],
       [106,  99, 111,  59],
       [ 76,  81,  59,  47]])

In [151]:
B

array([[2, 4, 4, 2],
       [2, 7, 3, 6],
       [8, 4, 6, 8],
       [7, 4, 0, 0]])

In [152]:
N = A.T

In [153]:
N[2:4] = B.T[2:4]
N.T

array([[179, 157,   4,   2],
       [157, 178,   3,   6],
       [106,  99,   6,   8],
       [ 76,  81,   0,   0]])

Если матрицы трехмерные:

In [164]:
C = np.array((3,np.random.randint(10),np.random.randint(10)))
C

array([3, 6, 0])