Документация -- https://docs.scipy.org/doc/numpy/reference/index.html

In [2]:
import numpy as np

## Генерация массива

In [29]:
a = np.array([[0, 1, 2],[3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
print(type(a)) # Тип переменной
print(a.ndim)  # Количество размерностей массива
print(a.shape) # Размеры
print(a.dtype) # Тип содержимого

<class 'numpy.ndarray'>
2
(2, 3)
int32


In [31]:
np.random.rand(5)

array([ 0.30016861,  0.60557133,  0.02820088,  0.06982125,  0.46415507])

In [32]:
np.random.randint(low=5, high=10)

5

Рандомно задать двумерный массив целых чисел 

In [33]:
n = np.random.randint(10, size=(np.random.randint(2,10),np.random.randint(2,10)))
n

array([[0, 3, 9, 3, 5, 5, 8, 5],
       [0, 4, 3, 6, 7, 6, 6, 7],
       [9, 8, 0, 4, 9, 7, 7, 9],
       [8, 3, 1, 2, 2, 6, 1, 3],
       [4, 2, 9, 0, 7, 0, 1, 3],
       [4, 3, 6, 6, 5, 2, 2, 9]])

Изменить тип элементов в предыдущем массиве на float.

In [34]:
n = np.array(n, dtype='float64')
n

array([[ 0.,  3.,  9.,  3.,  5.,  5.,  8.,  5.],
       [ 0.,  4.,  3.,  6.,  7.,  6.,  6.,  7.],
       [ 9.,  8.,  0.,  4.,  9.,  7.,  7.,  9.],
       [ 8.,  3.,  1.,  2.,  2.,  6.,  1.,  3.],
       [ 4.,  2.,  9.,  0.,  7.,  0.,  1.,  3.],
       [ 4.,  3.,  6.,  6.,  5.,  2.,  2.,  9.]])

Перемешать в нем элементы

In [35]:
np.random.shuffle(n)
n

array([[ 0.,  4.,  3.,  6.,  7.,  6.,  6.,  7.],
       [ 4.,  2.,  9.,  0.,  7.,  0.,  1.,  3.],
       [ 0.,  3.,  9.,  3.,  5.,  5.,  8.,  5.],
       [ 9.,  8.,  0.,  4.,  9.,  7.,  7.,  9.],
       [ 8.,  3.,  1.,  2.,  2.,  6.,  1.,  3.],
       [ 4.,  3.,  6.,  6.,  5.,  2.,  2.,  9.]])

Создать массив из чисел от 0 до 100

In [36]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Создать трехмерный массив, заполненный 0) нулями, 1) единицами.
Создать единичную матрицу.

In [37]:
np.zeros((3,np.random.randint(10),np.random.randint(10)))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [38]:
np.ones((3,np.random.randint(10),np.random.randint(10)))

array([[[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1

In [39]:
np.identity(np.random.randint(2,10))

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

## Cрезы

In [40]:
a = np.random.randint(low=0, high=10, size=(4, 5))
a

array([[0, 0, 8, 4, 4],
       [4, 9, 6, 1, 7],
       [5, 4, 3, 2, 1],
       [4, 4, 6, 1, 4]])

In [41]:
a[1]

array([4, 9, 6, 1, 7])

In [42]:
a[1, 2]

6

In [43]:
a[1][2]

6

Вывести массив, состоящий из 1-3 1) строк, 2) столбцов массива a

In [44]:
a[0:3]

array([[0, 0, 8, 4, 4],
       [4, 9, 6, 1, 7],
       [5, 4, 3, 2, 1]])

In [45]:
a[0:4,0:3]

array([[0, 0, 8],
       [4, 9, 6],
       [5, 4, 3],
       [4, 4, 6]])

Вывести массив, состоящий из 1) строк 2) столбцов массива a с четными индексами

In [46]:
np.array([a[line] for line in range(0,3,2)])

array([[0, 0, 8, 4, 4],
       [5, 4, 3, 2, 1]])

In [47]:
np.array([a[0:5, i] for i in range(0,5,2)]).T

array([[0, 8, 4],
       [4, 6, 7],
       [5, 3, 1],
       [4, 6, 4]])

Занулить 2 столбец массива a

In [48]:
a[:,1] = 0
a

array([[0, 0, 8, 4, 4],
       [4, 0, 6, 1, 7],
       [5, 0, 3, 2, 1],
       [4, 0, 6, 1, 4]])

Вывести массив той же размерности, что и a, где на месте каждого элемента из массива a будет стоять True или False в зависимости от того, больше ли этот элемент 1) 0, 2) 5 

In [49]:
np.array([[True if a[j][i]>0 else False for i in range(5)] for j in range(4)])

array([[False, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True]], dtype=bool)

In [50]:
np.array([[True if a[j][i]>5 else False for i in range(5)] for j in range(4)])

array([[False, False,  True, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False],
       [False, False,  True, False, False]], dtype=bool)

Составить массив из элементов массива a, больших 5

In [51]:
a[a>5]

array([8, 6, 7, 6])

## Линейная алгебра

Найти минимальный и максимальный элементы массива a, среднее арифметическое, медиану, сумму элементов и стандартно отклонение

In [52]:
np.amax(a)

8

In [53]:
np.amin(a)

0

In [54]:
np.mean(a)

3.0

In [55]:
np.median(a)

3.5

In [56]:
np.sum(a)

60

In [57]:
np.std(a)

2.5099800796022267

In [58]:
a

array([[0, 0, 8, 4, 4],
       [4, 0, 6, 1, 7],
       [5, 0, 3, 2, 1],
       [4, 0, 6, 1, 4]])

Отсортировать элементы в массиве a 1) по строкам 2) по столбцам

In [59]:
np.sort(a, axis=1)

array([[0, 0, 4, 4, 8],
       [0, 1, 4, 6, 7],
       [0, 1, 2, 3, 5],
       [0, 1, 4, 4, 6]])

In [60]:
np.sort(a, axis=0)

array([[0, 0, 3, 1, 1],
       [4, 0, 6, 1, 4],
       [4, 0, 6, 2, 4],
       [5, 0, 8, 4, 7]])

Транспонировать матрицу a

In [61]:
a.T

array([[0, 4, 5, 4],
       [0, 0, 0, 0],
       [8, 6, 3, 6],
       [4, 1, 2, 1],
       [4, 7, 1, 4]])

Произвести умножение матриц

In [62]:
A = np.matmul(a, a.T)
A

array([[ 96,  80,  36,  68],
       [ 80, 102,  47,  81],
       [ 36,  47,  39,  44],
       [ 68,  81,  44,  69]])

Найти ранг матрицы, ее определитель

In [63]:
np.linalg.matrix_rank(A)

4

In [64]:
np.linalg.det(A)

82943.999999999738

Решить систему линейных уравнений, заданных матрицей

In [65]:
b = np.array([2,3,7,0])
x = np.linalg.solve(A,b)

проверим правильность решения

In [66]:
np.allclose(np.dot(A, x), b)

True

## Операции

Выполнить поэлементное сложение и умножение матриц

In [67]:
B = np.random.randint(low=0, high=10, size=(4, 4))
B

array([[0, 7, 1, 6],
       [4, 0, 4, 7],
       [9, 5, 2, 8],
       [7, 1, 4, 6]])

In [68]:
A + B

array([[ 96,  87,  37,  74],
       [ 84, 102,  51,  88],
       [ 45,  52,  41,  52],
       [ 75,  82,  48,  75]])

In [69]:
A * B

array([[  0, 560,  36, 408],
       [320,   0, 188, 567],
       [324, 235,  78, 352],
       [476,  81, 176, 414]])

Превратить одномерный массив в двумерный с сохранением элементов

In [70]:
c = np.random.randint(low=0, high=10, size=(1,8))
c

array([[8, 4, 6, 3, 3, 0, 2, 8]])

In [71]:
np.reshape(c, (2,np.size(c)//2))

array([[8, 4, 6, 3],
       [3, 0, 2, 8]])

Добавить 1) строки 2) столбцы одного массива в другой (слить в один)

In [72]:
np.concatenate((A, B), axis=0)

array([[ 96,  80,  36,  68],
       [ 80, 102,  47,  81],
       [ 36,  47,  39,  44],
       [ 68,  81,  44,  69],
       [  0,   7,   1,   6],
       [  4,   0,   4,   7],
       [  9,   5,   2,   8],
       [  7,   1,   4,   6]])

In [73]:
np.concatenate((A, B), axis=1)

array([[ 96,  80,  36,  68,   0,   7,   1,   6],
       [ 80, 102,  47,  81,   4,   0,   4,   7],
       [ 36,  47,  39,  44,   9,   5,   2,   8],
       [ 68,  81,  44,  69,   7,   1,   4,   6]])

Заменить нулевые значения в массиве на среднее по строке

In [74]:
B

array([[0, 7, 1, 6],
       [4, 0, 4, 7],
       [9, 5, 2, 8],
       [7, 1, 4, 6]])

In [75]:
np.where(np.equal(B,0), np.ma.array(B, mask=np.equal(B,0)).mean(axis=0), B)

array([[ 6.66666667,  7.        ,  1.        ,  6.        ],
       [ 4.        ,  4.33333333,  4.        ,  7.        ],
       [ 9.        ,  5.        ,  2.        ,  8.        ],
       [ 7.        ,  1.        ,  4.        ,  6.        ]])

Поэкспериментировать со слиянием двух матриц. Добавить элементы одной на определенное место в другой (допустим, 3 и 4 столбец). Что, если матрицы трехмерные? Если не подходят размерности?

In [76]:
A

array([[ 96,  80,  36,  68],
       [ 80, 102,  47,  81],
       [ 36,  47,  39,  44],
       [ 68,  81,  44,  69]])

In [77]:
B

array([[0, 7, 1, 6],
       [4, 0, 4, 7],
       [9, 5, 2, 8],
       [7, 1, 4, 6]])

In [79]:
np.concatenate((A.T[0:2],B.T[2:4])).T

array([[ 96,  80,   1,   6],
       [ 80, 102,   4,   7],
       [ 36,  47,   2,   8],
       [ 68,  81,   4,   6]])

Слияние трехмерных матриц:

In [24]:
C = np.random.randint(10, size=(4,4,4))
C

array([[[2, 7, 3, 4],
        [4, 5, 9, 2],
        [0, 0, 5, 9],
        [5, 9, 9, 8]],

       [[0, 9, 5, 5],
        [0, 2, 7, 1],
        [8, 0, 6, 5],
        [3, 2, 2, 2]],

       [[5, 5, 8, 1],
        [5, 7, 0, 8],
        [0, 9, 1, 5],
        [5, 2, 1, 8]],

       [[9, 4, 1, 3],
        [6, 2, 2, 1],
        [6, 9, 7, 3],
        [2, 8, 6, 1]]])

In [25]:
D = np.random.randint(10, size=(4,4,4))
D

array([[[1, 6, 3, 0],
        [9, 2, 0, 8],
        [2, 5, 8, 4],
        [9, 2, 5, 0]],

       [[6, 6, 5, 3],
        [4, 9, 7, 6],
        [3, 5, 6, 8],
        [0, 7, 7, 5]],

       [[4, 2, 0, 8],
        [9, 8, 3, 6],
        [0, 9, 3, 8],
        [7, 2, 7, 7]],

       [[1, 2, 9, 0],
        [4, 2, 0, 5],
        [4, 3, 8, 4],
        [2, 5, 6, 3]]])

In [27]:
np.concatenate((C,D), axis=2)

array([[[2, 7, 3, 4, 1, 6, 3, 0],
        [4, 5, 9, 2, 9, 2, 0, 8],
        [0, 0, 5, 9, 2, 5, 8, 4],
        [5, 9, 9, 8, 9, 2, 5, 0]],

       [[0, 9, 5, 5, 6, 6, 5, 3],
        [0, 2, 7, 1, 4, 9, 7, 6],
        [8, 0, 6, 5, 3, 5, 6, 8],
        [3, 2, 2, 2, 0, 7, 7, 5]],

       [[5, 5, 8, 1, 4, 2, 0, 8],
        [5, 7, 0, 8, 9, 8, 3, 6],
        [0, 9, 1, 5, 0, 9, 3, 8],
        [5, 2, 1, 8, 7, 2, 7, 7]],

       [[9, 4, 1, 3, 1, 2, 9, 0],
        [6, 2, 2, 1, 4, 2, 0, 5],
        [6, 9, 7, 3, 4, 3, 8, 4],
        [2, 8, 6, 1, 2, 5, 6, 3]]])