Документация -- https://docs.scipy.org/doc/numpy/reference/index.html

In [254]:
import numpy as np

## Генерация массива

In [255]:
a = np.array([[0, 1, 2],[3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [256]:
print(type(a)) # Тип переменной
print(a.ndim)  # Количество размерностей массива
print(a.shape) # Размеры
print(a.dtype) # Тип содержимого

<class 'numpy.ndarray'>
2
(2, 3)
int32


In [257]:
np.random.rand(5)

array([ 0.14711039,  0.36703283,  0.49815038,  0.20881376,  0.06505809])

In [258]:
np.random.randint(low=5, high=10)

8

Рандомно задать двумерный массив целых чисел 

In [259]:
n = np.random.randint(10, size=(np.random.randint(2,10),np.random.randint(2,10)))
n

array([[9, 5, 8, 3, 7, 8, 6, 1],
       [8, 1, 3, 8, 9, 4, 8, 8],
       [7, 1, 4, 4, 1, 6, 8, 6],
       [5, 5, 3, 9, 4, 3, 4, 6],
       [7, 1, 1, 9, 4, 0, 5, 0],
       [8, 7, 5, 1, 1, 1, 3, 0],
       [1, 2, 9, 4, 8, 9, 1, 3],
       [9, 4, 3, 4, 4, 8, 0, 2]])

Изменить тип элементов в предыдущем массиве на float.

In [260]:
n = np.array(n, dtype='float64')
n

array([[ 9.,  5.,  8.,  3.,  7.,  8.,  6.,  1.],
       [ 8.,  1.,  3.,  8.,  9.,  4.,  8.,  8.],
       [ 7.,  1.,  4.,  4.,  1.,  6.,  8.,  6.],
       [ 5.,  5.,  3.,  9.,  4.,  3.,  4.,  6.],
       [ 7.,  1.,  1.,  9.,  4.,  0.,  5.,  0.],
       [ 8.,  7.,  5.,  1.,  1.,  1.,  3.,  0.],
       [ 1.,  2.,  9.,  4.,  8.,  9.,  1.,  3.],
       [ 9.,  4.,  3.,  4.,  4.,  8.,  0.,  2.]])

Перемешать в нем элементы

In [261]:
np.random.shuffle(n)
n

array([[ 1.,  2.,  9.,  4.,  8.,  9.,  1.,  3.],
       [ 9.,  5.,  8.,  3.,  7.,  8.,  6.,  1.],
       [ 8.,  1.,  3.,  8.,  9.,  4.,  8.,  8.],
       [ 8.,  7.,  5.,  1.,  1.,  1.,  3.,  0.],
       [ 7.,  1.,  4.,  4.,  1.,  6.,  8.,  6.],
       [ 5.,  5.,  3.,  9.,  4.,  3.,  4.,  6.],
       [ 9.,  4.,  3.,  4.,  4.,  8.,  0.,  2.],
       [ 7.,  1.,  1.,  9.,  4.,  0.,  5.,  0.]])

Создать массив из чисел от 0 до 100

In [262]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Создать трехмерный массив, заполненный 0) нулями, 1) единицами.
Создать единичную матрицу.

In [263]:
np.zeros((3,np.random.randint(10),np.random.randint(10)))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [264]:
np.ones((3,np.random.randint(10),np.random.randint(10)))

array([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

In [265]:
np.identity(np.random.randint(2,10))

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

## Cрезы

In [266]:
a = np.random.randint(low=0, high=10, size=(4, 5))
a

array([[8, 5, 2, 7, 9],
       [9, 1, 9, 6, 7],
       [7, 1, 7, 1, 6],
       [3, 7, 9, 2, 9]])

In [267]:
a[1]

array([9, 1, 9, 6, 7])

In [268]:
a[1, 2]

9

In [269]:
a[1][2]

9

Вывести массив, состоящий из 1-3 1) строк, 2) столбцов массива a

In [270]:
a[0:3]

array([[8, 5, 2, 7, 9],
       [9, 1, 9, 6, 7],
       [7, 1, 7, 1, 6]])

In [271]:
a[0:4,0:3]

array([[8, 5, 2],
       [9, 1, 9],
       [7, 1, 7],
       [3, 7, 9]])

Вывести массив, состоящий из 1) строк 2) столбцов массива a с четными индексами

In [272]:
np.array([a[line] for line in range(0,3,2)])

array([[8, 5, 2, 7, 9],
       [7, 1, 7, 1, 6]])

In [273]:
np.array([a[0:5, i] for i in range(0,5,2)]).T

array([[8, 2, 9],
       [9, 9, 7],
       [7, 7, 6],
       [3, 9, 9]])

Занулить 2 столбец массива a

In [274]:
a[:,1] = 0
a

array([[8, 0, 2, 7, 9],
       [9, 0, 9, 6, 7],
       [7, 0, 7, 1, 6],
       [3, 0, 9, 2, 9]])

Вывести массив той же размерности, что и a, где на месте каждого элемента из массива a будет стоять True или False в зависимости от того, больше ли этот элемент 1) 0, 2) 5 

In [275]:
np.array([[True if a[j][i]>0 else False for i in range(5)] for j in range(4)])

array([[ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True]], dtype=bool)

In [276]:
np.array([[True if a[j][i]>5 else False for i in range(5)] for j in range(4)])

array([[ True, False, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True, False,  True],
       [False, False,  True, False,  True]], dtype=bool)

Составить массив из элементов массива a, больших 5

In [277]:
a[a>5]

array([8, 7, 9, 9, 9, 6, 7, 7, 7, 6, 9, 9])

## Линейная алгебра

Найти минимальный и максимальный элементы массива a, среднее арифметическое, медиану, сумму элементов и стандартно отклонение

In [278]:
np.amax(a)

9

In [279]:
np.amin(a)

0

In [280]:
np.mean(a)

5.0499999999999998

In [281]:
np.median(a)

6.5

In [282]:
np.sum(a)

101

In [283]:
np.std(a)

3.499642838919423

In [284]:
a

array([[8, 0, 2, 7, 9],
       [9, 0, 9, 6, 7],
       [7, 0, 7, 1, 6],
       [3, 0, 9, 2, 9]])

Отсортировать элементы в массиве a 1) по строкам 2) по столбцам

In [285]:
np.sort(a, axis=1)

array([[0, 2, 7, 8, 9],
       [0, 6, 7, 9, 9],
       [0, 1, 6, 7, 7],
       [0, 2, 3, 9, 9]])

In [286]:
np.sort(a, axis=0)

array([[3, 0, 2, 1, 6],
       [7, 0, 7, 2, 7],
       [8, 0, 9, 6, 9],
       [9, 0, 9, 7, 9]])

Транспонировать матрицу a

In [287]:
a.T

array([[8, 9, 7, 3],
       [0, 0, 0, 0],
       [2, 9, 7, 9],
       [7, 6, 1, 2],
       [9, 7, 6, 9]])

Произвести умножение матриц

In [288]:
A = np.matmul(a, a.T)
A

array([[198, 195, 131, 137],
       [195, 247, 174, 183],
       [131, 174, 135, 140],
       [137, 183, 140, 175]])

Найти ранг матрицы, ее определитель

In [289]:
np.linalg.matrix_rank(A)

4

In [290]:
np.linalg.det(A)

3686400.0000000014

Решить систему линейных уравнений, заданных матрицей

In [291]:
b = np.array([2,3,7,0])
x = np.linalg.solve(A,b)

проверим правильность решения

In [292]:
np.allclose(np.dot(A, x), b)

True

## Операции

Выполнить поэлементное сложение и умножение матриц

In [293]:
B = np.random.randint(low=0, high=10, size=(4, 4))
B

array([[8, 1, 0, 0],
       [6, 9, 1, 6],
       [0, 4, 6, 3],
       [0, 7, 7, 4]])

In [294]:
A + B

array([[206, 196, 131, 137],
       [201, 256, 175, 189],
       [131, 178, 141, 143],
       [137, 190, 147, 179]])

In [295]:
A * B

array([[1584,  195,    0,    0],
       [1170, 2223,  174, 1098],
       [   0,  696,  810,  420],
       [   0, 1281,  980,  700]])

Превратить одномерный массив в двумерный с сохранением элементов

In [296]:
c = np.random.randint(low=0, high=10, size=(1,8))
c

array([[3, 5, 5, 2, 2, 3, 4, 8]])

In [297]:
np.reshape(c, (2,np.size(c)//2))

array([[3, 5, 5, 2],
       [2, 3, 4, 8]])

Добавить 1) строки 2) столбцы одного массива в другой (слить в один)

In [298]:
np.concatenate((A, B), axis=0)

array([[198, 195, 131, 137],
       [195, 247, 174, 183],
       [131, 174, 135, 140],
       [137, 183, 140, 175],
       [  8,   1,   0,   0],
       [  6,   9,   1,   6],
       [  0,   4,   6,   3],
       [  0,   7,   7,   4]])

In [299]:
np.concatenate((A, B), axis=1)

array([[198, 195, 131, 137,   8,   1,   0,   0],
       [195, 247, 174, 183,   6,   9,   1,   6],
       [131, 174, 135, 140,   0,   4,   6,   3],
       [137, 183, 140, 175,   0,   7,   7,   4]])

Заменить нулевые значения в массиве на среднее по строке

In [300]:
B

array([[8, 1, 0, 0],
       [6, 9, 1, 6],
       [0, 4, 6, 3],
       [0, 7, 7, 4]])

In [301]:
np.where(np.equal(B,0), np.ma.array(B, mask=np.equal(B,0)).mean(axis=0), B)

array([[ 8.        ,  1.        ,  4.66666667,  4.33333333],
       [ 6.        ,  9.        ,  1.        ,  6.        ],
       [ 7.        ,  4.        ,  6.        ,  3.        ],
       [ 7.        ,  7.        ,  7.        ,  4.        ]])

Поэкспериментировать со слиянием двух матриц. Добавить элементы одной на определенное место в другой (допустим, 3 и 4 столбец). Что, если матрицы трехмерные? Если не подходят размерности?

In [307]:
A

array([[198, 195, 131, 137],
       [195, 247, 174, 183],
       [131, 174, 135, 140],
       [137, 183, 140, 175]])

In [308]:
B

array([[8, 1, 0, 0],
       [6, 9, 1, 6],
       [0, 4, 6, 3],
       [0, 7, 7, 4]])

In [311]:
np.transpose(A)


array([[198, 195, 131, 137],
       [195, 247, 174, 183],
       [131, 174, 135, 140],
       [137, 183, 140, 175]])