Документация -- https://docs.scipy.org/doc/numpy/reference/index.html

In [1]:
import numpy as np

## Генерация массива

In [2]:
a = np.array([[0, 1, 2],[3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
print(type(a)) # Тип переменной
print(a.ndim)  # Количество размерностей массива
print(a.shape) # Размеры
print(a.dtype) # Тип содержимого

<class 'numpy.ndarray'>
2
(2, 3)
int32


In [4]:
np.random.rand(5)

array([0.31532278, 0.69721333, 0.98452614, 0.41448146, 0.56502694])

In [8]:
np.random.randint(low=5, high=10)

5

Рандомно задать двумерный массив целых чисел 

In [26]:
np.array([np.random.randint(1, 10, ) for n in range(np.random.randint(low=2, high=10))])

array([[4, 4, 5, 4, 3],
       [2, 2, 4, 1, 5],
       [5, 6, 6, 6, 8],
       [3, 1, 3, 7, 3],
       [8, 6, 3, 6, 7],
       [8, 4, 3, 9, 2],
       [2, 8, 1, 5, 4],
       [9, 9, 2, 9, 6],
       [9, 5, 5, 8, 7]])

In [70]:
n = np.random.randint(10, size=(np.random.randint(2,10),np.random.randint(2,10)))
n

array([[3, 1, 7],
       [2, 7, 3],
       [3, 6, 3],
       [9, 4, 0],
       [9, 4, 7]])

Изменить тип элементов в предыдущем массиве на float.

In [71]:
n = np.array(n, dtype='float64')
n

array([[3., 1., 7.],
       [2., 7., 3.],
       [3., 6., 3.],
       [9., 4., 0.],
       [9., 4., 7.]])

Перемешать в нем элементы

In [72]:
np.random.shuffle(n)
n

array([[9., 4., 7.],
       [3., 1., 7.],
       [3., 6., 3.],
       [2., 7., 3.],
       [9., 4., 0.]])

Создать массив из чисел от 0 до 100

In [86]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Создать трехмерный массив, заполненный 0) нулями, 1) единицами.
Создать единичную матрицу.

In [99]:
np.zeros((3,np.random.randint(10),np.random.randint(10)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [101]:
np.ones((3,np.random.randint(10),np.random.randint(10)))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [107]:
np.identity(np.random.randint(2,10))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Cрезы

In [108]:
a = np.random.randint(low=0, high=10, size=(4, 5))
a

array([[9, 8, 4, 6, 8],
       [0, 5, 9, 3, 9],
       [3, 1, 5, 0, 5],
       [7, 7, 2, 8, 5]])

In [109]:
a[1]

array([0, 5, 9, 3, 9])

In [112]:
a[1, 2]

9

In [113]:
a[1][2]

9

Вывести массив, состоящий из 1-3 1) строк, 2) столбцов массива a

In [115]:
a[0:3]

array([[9, 8, 4, 6, 8],
       [0, 5, 9, 3, 9],
       [3, 1, 5, 0, 5]])

In [141]:
a[0:4,0:3]

array([[9, 8, 4],
       [0, 5, 9],
       [3, 1, 5],
       [7, 7, 2]])

Вывести массив, состоящий из 1) строк 2) столбцов массива a с четными индексами

In [143]:
np.array([a[line] for line in range(0,3,2)])

array([[9, 8, 4, 6, 8],
       [3, 1, 5, 0, 5]])

In [153]:
np.array([a[0:5, i] for i in range(0,5,2)]).T

array([[9, 4, 8],
       [0, 9, 9],
       [3, 5, 5],
       [7, 2, 5]])

Занулить 2 столбец массива a

In [154]:
a[:,1] = 0
a

array([[9, 0, 4, 6, 8],
       [0, 0, 9, 3, 9],
       [3, 0, 5, 0, 5],
       [7, 0, 2, 8, 5]])

Вывести массив той же размерности, что и a, где на месте каждого элемента из массива a будет стоять True или False в зависимости от того, больше ли этот элемент 1) 0, 2) 5 

In [167]:
np.array([[True if a[j][i]>0 else False for i in range(5)] for j in range(4)])

array([[ True, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True, False,  True,  True,  True]])

In [168]:
np.array([[True if a[j][i]>5 else False for i in range(5)] for j in range(4)])

array([[ True, False, False,  True,  True],
       [False, False,  True, False,  True],
       [False, False, False, False, False],
       [ True, False, False,  True, False]])

Составить массив из элементов массива a, больших 5

In [201]:
np.array([a[i][j] for i in range(0,5) for j in range(0,5) if a[i][j]>5 ])

IndexError: index 4 is out of bounds for axis 0 with size 4

In [211]:
np.array([a[i][i] for i in range(len(a[i]-2))])

IndexError: index 4 is out of bounds for axis 0 with size 4

## Линейная алгебра

Найти минимальный и максимальный элементы массива a, среднее арифметическое, медиану, сумму элементов и стандартно отклонение

Отсортировать элементы в массиве a 1) по строкам 2) по столбцам

Транспонировать матрицу a

Произвести умножение матриц

Найти ранг матрицы, ее определитель

Решить систему линейных уравнений, заданных матрицей

## Операции

Выполнить поэлементное сложение и умножение матриц

Превратить одномерный массив в двумерный с сохранением элементов

Добавить 1) строки 2) столбцы одного массива в другой (слить в один)

Заменить нулевые значения в массиве на среднее по строке

Поэкспериментировать со слиянием двух матриц. Добавить элементы одной на определенное место в другой (допустим, 3 и 4 столбец). Что, если матрицы трехмерные? Если не подходят размерности?