In [1]:
import tensorflow as tf

In [37]:
hello = tf.constant('Hello')
hello

<tf.Tensor 'Const_9:0' shape=() dtype=string>

In [38]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [39]:
world = tf.constant(', World')
result = hello + world
type(result)

tensorflow.python.framework.ops.Tensor

In [40]:
sess = tf.Session()
result = sess.run(hello+world)

In [41]:
result
#результат - бинарный

b'Hello, World'

In [42]:
result.decode()

'Hello, World'

In [43]:
a = tf.constant(1)
b = tf.constant(2)

In [44]:
sess.run(a+b)

3

In [45]:
#сессии рекомендуется закрывать
sess.close()

Тензор 1-го порядка - скаляр  
Тензор 2-го порядка - матрица  
Тензор 3-го порядка - куб  
и т.д.

In [59]:
const = tf.constant([[1],[2],[3]])
fill_mat = tf.fill((4,4), 10) #матрица 4х4, все ячейки заплнены числом 10
zero_mat = tf.zeros((4,4)) #нулевая матрица
ones_mat = tf.ones((3,3))  #единичная матрица
eye_mat = tf.eye(5,5)  #диагональная матрица с единицами

Нормальное распределение

In [47]:
myrandn = tf.random_normal((4,4), mean=0, stddev=0.5)
#параметры: размер матрицы 4х4, среднее (центр шляпки) 0, стандартное отклонение 0.5

Стандартное распределение

In [48]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

Создадим сессию

In [61]:
ops = [const, fill_mat, zero_mat, ones_mat, eye_mat, myrandn, myrandu]
sess = tf.InteractiveSession()  #сессия для дебага/

c:\users\aaleshin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [62]:
for op in ops:
    print(op.eval())  #выведем все значения переменных

[[1]
 [2]
 [3]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 0.17410634 -0.22637568 -0.28447676 -0.39990538]
 [-0.9565684  -0.33189133 -0.36935404 -0.88517946]
 [ 0.1149838  -0.06880057  0.21325895  0.05077209]
 [ 0.49025914  0.33689806 -0.08563619 -0.511215  ]]
[[0.00661623 0.2293756  0.7646104  0.44176185]
 [0.80497575 0.6179023  0.41671586 0.9135951 ]
 [0.65028846 0.8576977  0.8583112  0.4400202 ]
 [0.58076537 0.00740242 0.664827   0.5917945 ]]


In [63]:
A = tf.constant([[1,2],[3,4]])
B = tf.constant([[10],[100]])

In [65]:
B.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [67]:
res = tf.matmul(A,B)

In [68]:
res.eval()

array([[210],
       [430]])