In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(1)
b = tf.constant(2)

with tf.Session() as sess:
    result = sess.run(a+b)
result

3

In [4]:
tf.get_default_graph()  #создаается граф по умолчанию

In [5]:
g = tf.Graph()
print(g)

In [6]:
graph_one = tf.get_default_graph()
graph_two = tf.Graph()

In [8]:
graph_one is tf.get_default_graph()  #является ли графом по умолчанию

True

In [11]:
graph_two is tf.get_default_graph()

False

Чтобы провести вычисления с недефолтным графом:

## Variables and Placeholders

In [21]:
sess = tf.InteractiveSession()

In [22]:
mytensor = tf.random_uniform((4,4), minval=0, maxval=100)  #матрица 4х4 с случайными числами от 0 до 100
myvar = tf.Variable(initial_value=mytensor)
myvar

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>

In [28]:
mytensor.eval()  #здесь eval можно сделать только с тензором, т.к. переменная еще не инициализирована

array([[38.237072 , 13.789225 , 93.336525 , 75.04493  ],
       [61.762573 ,  1.4724255, 11.056768 ,  8.518958 ],
       [52.08671  ,  6.778002 , 86.33363  , 12.204826 ],
       [21.407913 , 14.655781 , 22.044897 , 19.04652  ]], dtype=float32)

После создания переменной необходимо ее инициализировать

In [29]:
init = tf.global_variables_initializer()
init.run()

In [30]:
myvar.eval()

array([[99.68474 , 30.987883, 81.706985, 48.915817],
       [65.76578 , 18.340933, 42.216396, 32.3269  ],
       [37.160374, 84.25418 , 93.42767 , 12.345767],
       [77.00352 , 48.192085, 14.77145 , 79.93692 ]], dtype=float32)

In [32]:
sess.run(myvar)

array([[99.68474 , 30.987883, 81.706985, 48.915817],
       [65.76578 , 18.340933, 42.216396, 32.3269  ],
       [37.160374, 84.25418 , 93.42767 , 12.345767],
       [77.00352 , 48.192085, 14.77145 , 79.93692 ]], dtype=float32)

In [36]:
ph1 = tf.placeholder(tf.float64)
ph2 = tf.placeholder(tf.int64, shape=(None, 5))  #матрица с неизвестным кол-вом строк и 5 столбцами