# Задача регрессии

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[45.82954989, 85.10848298, 83.57215799,  3.43932033, 89.88980871],
       [79.9796513 , 60.46567162, 60.23174231, 77.03352572, 91.74178607],
       [85.80681992, 39.60272081, 98.55551146, 78.54239171, 13.59697626],
       [98.58507908, 80.90209486, 46.49360849, 39.07642491, 52.42096505],
       [ 0.9321601 , 27.10916616, 67.81176993, 49.56516876, 65.70508858]])

In [4]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[50.15137207],
       [73.79207145],
       [66.15224007],
       [78.51940264],
       [60.68521872]])

In [9]:
a = tf.placeholder(tf.float16)
b = tf.placeholder(tf.float16)
add_op = a+b  #вычислительный граф

In [10]:
with tf.Session() as sess:
    add_res = sess.run(add_op, feed_dict={a:rand_a, b:rand_b})  #ключ - placeholders, значение - variables
    print(add_res)

[[ 96.   135.2  133.8   53.6  140.  ]
 [153.8  134.2  134.   150.9  165.5 ]
 [152.   105.75 164.8  144.8   79.75]
 [177.   159.4  125.   117.56 130.9 ]
 [ 61.62  87.8  128.5  110.25 126.4 ]]


In [14]:
mul_op = a*b

In [15]:
with tf.Session() as sess:
    mul_res = sess.run(mul_op, feed_dict={a:rand_a, b:rand_b})
    print(mul_res)

[[2300.   4268.   4190.    172.5  4508.  ]
 [5904.   4464.   4444.   5690.   6772.  ]
 [5676.   2618.   6516.   5196.    899.  ]
 [7736.   6348.   3650.   3066.   4110.  ]
 [  56.56 1645.   4116.   3008.   3986.  ]]


#### Предскажем, сколько будет зарабатывать студент через несколько лет

y = wx + b

In [20]:
n_features = 10
n_neurons = 3

In [24]:
x = tf.placeholder(tf.float32, (None, n_features))

In [25]:
b = tf.Variable(tf.zeros([n_neurons]))  #нули по кол-ву нейронов
w = tf.Variable(tf.random_normal([n_features, n_neurons]))  #матрица 10х3

In [26]:
xw = tf.matmul(x,w)

In [27]:
z = tf.add(xw, b)  #добавляем свободный член

In [29]:
a = tf.sigmoid(z)

In [30]:
init = tf.global_variables_initializer()

In [35]:
with tf.Session() as sess:
    sess.run(init)
    output = sess.run(a, feed_dict={x:np.random.random([1, n_features])})

In [36]:
output

array([[0.53789604, 0.92461956, 0.88826925]], dtype=float32)

Вероятности принадлежности человека к классам доходов (высокий/средний/низкий)